# Generated by Django 4.0.6 on 2022-09-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
    ]
