# Generated by Django 4.0.6 on 2022-10-03 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customer_email_remove_customer_first_name_and_more'),
        ('products', '0008_remove_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customerpyth', to='accounts.customer'),
        ),
    ]
